#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "player.h" 
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/title_screen.h"
#include "images/floorImage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  drawFullScreenImageDMA(title_screen);

  // Initialize player
  Player player;
  initPlayer(&player);


  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    //if (reset button pressed) {drawfullscreenimg and reset variables}
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        ;
        
        // Start Button
        int btnWidth = 90;
        int btnHeight = 25;
        int btnX = (WIDTH - btnWidth) / 2;
        int btnY = (HEIGHT - btnHeight) / 2;

        u16 btnColor = PINK;
        drawRectDMA(btnY, btnX, btnWidth, btnHeight, btnColor);

        // Button text
        drawCenteredString(btnY + btnHeight/2 - 4, btnX, btnWidth, 8, "PRESS ENTER", WHITE);
        
        // Button functionality
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          // Draw floor
          drawImageDMA(HEIGHT - FLOOR_HEIGHT, 0, WIDTH, FLOOR_HEIGHT, floorImage);
          state = PLAY;
        }
        break;
      
      case PLAY:
        // background - not floor
        drawRectDMA(0, 0, WIDTH, HEIGHT - FLOOR_HEIGHT, WHITE);
        
        // Update and draw player
        updatePlayer(&player, currentButtons);
        drawPlayer(&player);
        
        // Debug: Show player position (optional)
        char posText[30];
        sprintf(posText, "X: %d Y: %d", player.x, player.y);
        drawString(5, 5, posText, WHITE);
        
        // Return to title screen
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            drawFullScreenImageDMA(title_screen);
            state = START;
            initPlayer(&player); // Reset player position
        }

        break;
      case WIN:

        // state = ?
        break;
      case LOSE:

        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
